using System;
using System.IO;
using System.IO.Compression;

namespace CWConsoleApp17_02_SW
{
	class Program
	{
		static void Main(string[] args)
		{
			var gen = new RandomDataGenerator();
			gen.RandomDataGenerationDone += Gen_RandomDataGenerationDone;

			gen.RandomDataGenerated += Gen_RandomDataGenerated;
			byte[] data = gen.GetRandomData(10000, 1000);
			string result = Convert.ToBase64String(data);
			Console.WriteLine(result);


			File.WriteAllBytes("data.txt", data);
		}

		private static void Gen_RandomDataGenerated(int byteDone, int totalBytes)
		{
			Console.WriteLine($"Generated byte {byteDone} in {totalBytes}");
		}

		private static void Gen_RandomDataGenerationDone(object sender, EventArgs e)
		{
			Console.WriteLine("WorkDone");
		}
	}
}
